# Generated by Django 3.1.7 on 2021-03-22 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(default='')),
                ('lista', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='listas.lista')),
            ],
            options={
                'ordering': ('id',),
                'unique_together': {('lista', 'texto')},
            },
        ),
    ]
