# Generated by Django 3.1.7 on 2021-05-24 23:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listas', '0002_lista_duenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='compartida_con',
            field=models.ManyToManyField(related_name='listas_compartidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
