# Generated by Django 3.1.7 on 2021-03-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0002_item_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='text',
            new_name='texto',
        ),
    ]
