# Generated by Django 3.1.7 on 2021-03-17 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0004_lista'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='lista',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='listas.lista'),
        ),
    ]
