# Generated by Django 3.1.7 on 2021-03-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0003_auto_20210317_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
