# Generated by Django 3.1.7 on 2021-03-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0005_item_lista'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('id',)},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('lista', 'texto')},
        ),
    ]
